version: '3'
services:
  ide:
    image: davidliyutong/code-server-speit:v4.16.1-kathara
    ports:
      - 8080:80
    privileged: true
    volumes:
      - ./data/docker:/var/lib/docker
      - ./data/home:/home/ubuntu
      - ./data/log:/var/lib/log
