apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-pvc-{{ID}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # CHANGEME Storage Limit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: apps.code-server-{{ID}}
  name: code-server-{{ID}}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: apps.code-server-{{ID}}
  template:
    metadata:
      labels:
        k8s-app: apps.code-server-{{ID}}
    spec:
      containers:
      - image: davidliyutong/code-server-ice3302p:4.7.0 # CHANGEME
        imagePullPolicy: IfNotPresent
        name: container-0
        ports:
        - containerPort: 8080
          name: 8080tcp
          protocol: TCP
        resources: # CHANGEME
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: 50m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /root
          name: home
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: code-server-pvc-{{ID}}
---
apiVersion: v1
kind: Service
metadata:
  name: code-server-svc-{{ID}}
spec:
  ports:
  - name: 8080tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: apps.code-server-{{ID}}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: coder-server-ingress-{{ID}}
spec:
  ingressClassName: public
  rules:
  - host: example.org # CHANGEME
    http:
      paths:
      - backend:
          service:
            name: code-server-svc-{{ID}}
            port:
              number: 8080
        path: /{{ID}}(/|$)(.*)
        pathType: Prefix
  tls:
  - hosts:
    - example.org # CHANGEME hostname
    secretName: tls-example-org # CHANGEME TLS Secret